### ISSUE TITLE
Long TX on boot and manual TX on TTGO-T-BEAM

### ISSUE THREAD

**Issue by ghost** [richonguzman/LoRa_APRS_Tracker#100]
Bug:
On first boot after unit gets valid GPS signal, first TX takes ~35 seconds to complete,
Not seen the unit do any further smart beaconing, doing a manual TX (central button short press) it does same where it takes 35s to TX

Expected behavior:
Normally TX takes approx 2-5s on average

![WhatsApp Image 2024-05-14 at 13 19 18_c874b2fe](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/48376949/e06e6294-4560-41e0-a2b9-68059a53c5b3)

Desktop
    OS: Win11 Pro
    PlatformIO Version: 1.89.1
    Firmware Version: 14-05-2024

Board name: LILYGO TTGO T-BEAM-v1_2

Board has had a complete erase and rebuild, still present

**Comment by richonguzman** [comment]
this is very strange as I've been testing it here with V.1, V1.2, HELTEC WirelessTracker and other DIY boards and all handle it like a normal message


should we check in detail the filesystem configuration?

**Comment by ghost** [comment]
Sure, can send over a copy of the conf.json for what I used for the tracker - no other variables anywhere else were changed, 
e.g. open VSS, created fresh download, let it update platform.io "as normal" , once settled added in the adjusted variables where needed (callsign, comment etc) most of the other settings left to default certainly for Freq and smart beaconing

**Comment by richonguzman** [comment]
> Sure, can send over a copy of the conf.json for what I used for the tracker - no other variables anywhere else were changed, e.g. open VSS, created fresh download, let it update platform.io "as normal" , once settled added in the adjusted variables where needed (callsign, comment etc) most of the other settings left to default certainly for Freq and smart beaconing

if you have telegram look for me (the same user as here on github) to see in detail your case

**Comment by ghost** [comment]
Issues now resolved, 
wiping / full erase of flash and rebuilding, leaving default "NOCALL-7" config on and building, then adding in "simple" fields like 1 callsign no other changes - upload, test, clear then add in the next conf changes e.g. comment and other secondary/tertiary SSID's with comments, then lastly "other" field for adding batteryinfo and changing from android to iphone 

Issue no longer presented and was TX'ing at normal rate and being received on local igate showing raw packets and comments 

thanks for input Ricardo for sense checking
