### ISSUE TITLE
Feature Request add nrf52840 microcontroller support 

### ISSUE THREAD

**Issue by drtechga** [richonguzman/LoRa_APRS_Tracker#101]
Hello Ricardo, It would be nice to nrf52840 support to greatly increased the battery life for a tracker, like the meshtastic people have done. How hard would it be to add support for it?

Thanks,
KK4JMW

**Comment by richonguzman** [comment]
Hi,

I'm currently working on some basic NRF52840 board to try to add this also for tracker and igates....

NOTE: I only have a T-echo here so this is the one I'm trying to make it run

**Comment by richonguzman** [comment]
i will try to get some more NRF52 boards to add to this Firmware

**Comment by richonguzman** [comment]
i will receive soon the GPS for RAK module and will add it as soon as I can
