### ISSUE TITLE
No screen rotation, TTGO Lilygo T-Beam S3 Supreme V3

### ISSUE THREAD

**Issue by Charly1000** [richonguzman/LoRa_APRS_Tracker#103]
180 degrees screen rotation doesn't work.
It's always one direction.

**Comment by richonguzman** [comment]
can you test adding this code 


`if (Config.display.turn180) {
                display.setRotation(2);
 }`

to /src/display.cpp


between line 112 and 113??

<img width="533" alt="Captura de pantalla 2024-05-19 a la(s) 03 56 22" src="https://github.com/richonguzman/LoRa_APRS_Tracker/assets/69999130/29704882-0885-42ab-8812-ce02a97cf091">

**Comment by Charly1000** [comment]
Sure, I will test it and report back

**Comment by Charly1000** [comment]
RESOLVED
screen rotation is working now. 
now you can set true and false and screen rotation works.
