### ISSUE TITLE
WX data? Comment? Looks like matrix :), TTGO Lilygo T-Beam S3 Supreme V3

### ISSUE THREAD

**Issue by Charly1000** [richonguzman/LoRa_APRS_Tracker#104]
built on WX-data works perfect on built-in screen. 
But in example on the website aprs.fi it looks as you can see on the picture. 

![image](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/78156331/b0eb746e-043a-4060-9bfc-0cb6017b1a72)

**Comment by richonguzman** [comment]
Hi

I would need to see your raw packets , what is your callsign and ssid used for this?

**Comment by Charly1000** [comment]
yes, of course: DO3MMC-7

**Comment by richonguzman** [comment]
> yes, of course: DO3MMC-7

can you change the MIC-E encoding to "" (yes, no MIC-E enconding at all)


I didn't test if sending Wx Packet with MIC-E encoding worked before

**Comment by Charly1000** [comment]
MIC-E is full off. 
it doesn't work. Have a look on the raw data

**Comment by richonguzman** [comment]
its working right now as I've checked

**Comment by Charly1000** [comment]
You're right. 
But what's the code? .../...g...t080r.... ..?
and how it's possible to write own comments?

**Comment by richonguzman** [comment]
you can add a Comment on /data/tracker_conf.json and upload filesystem again. (Check also that comments gets send once at X number of Tx packets. This number can be also changed in tracker_conf.json file as "sendCommentAfterXBeacons".

PS: 


I've update the code with this corrections on display ON and OFF, screen brightness and also to send the Wx Data at start and don't wait 10 min at first Wx data Tx

please update the code from github and test it all

**Comment by Charly1000** [comment]
Perfect.
RESOLVED. 
it's working fine now

Thank you sooo much

**Comment by richonguzman** [comment]
now Wx data won't be sended over Mic-E encoding even though all gps positions are in MiC-E
