### ISSUE TITLE
Eco mode, TTGO Lilygo T-Beam S3 Supreme V3

### ISSUE THREAD

**Issue by Charly1000** [richonguzman/LoRa_APRS_Tracker#105]
Eco-mode on/off has no impact. Screen is always on

**Comment by richonguzman** [comment]
do you run your board with SH1106 or SSD1306 screen?

**Comment by Charly1000** [comment]
It should be SH1106


![image](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/78156331/43443d19-0546-44fb-bdf3-9c60f5a6c4ed)

**Comment by richonguzman** [comment]
can you test modding the following?


/SRC/display.cpp  , line 132 on void display_toggle(bool toggle)...

I've added the "test code" lines to see if this works on SH1106 to turn screen on and off

<img width="539" alt="Captura de pantalla 2024-05-19 a la(s) 04 26 25" src="https://github.com/richonguzman/LoRa_APRS_Tracker/assets/69999130/69e1a68e-07d0-4d1e-aefd-b84023f17cf7">

**Comment by Charly1000** [comment]
Perfect. RESOLVED.
it's working fine now.
