### ISSUE TITLE
no Battery Stat., TTGO Lilygo T-Beam S3 Supreme V3

### ISSUE THREAD

**Issue by Charly1000** [richonguzman/LoRa_APRS_Tracker#107]
It doesn't send the status about the battery percentage.
The built-in screen displays everything perfectly.

**Comment by richonguzman** [comment]
download latest update from github (it should work now)

**Comment by Charly1000** [comment]
yes, you're right. RESOLVED :) thank you.
now, I believe it's time to speak about "full support for the TTGO Lilygo T-Beam S3 Supreme V3." :)
