### ISSUE TITLE
Static IP address

### ISSUE THREAD

**Issue by tk5ep** [richonguzman/LoRa_APRS_Tracker#11]
Edit : Oops !
It was concerning the iGate !

Hi Ricardo,

Not a issue, but an improvement request.

It would be nice to have the choice between DHCP IP address or static. ;-)

73 Patrick TK5EP

**Comment by richonguzman** [comment]
Hi Patrick, why is this needed?

This gets in conflict somehow with the OTA part and also the ip could be defined easy in the WiFi router

Saludos,

Ricardo / Richon
(Enviado desde mi celular a tubos)

El 22-07-2023, a las 11:36, Patrick EGLOFF ***@***.***> escribió:

﻿

Hi Ricardo,
Not a issue, but an improvement request.

It would be nice to have the choice between DHCP IP address or static. ;-)

73 Patrick TK5EP

**Comment by tk5ep** [comment]
Hi Ricardo,

Why ?
It's sometimes needed in a  private network where there is no DHCP for security reason and you don't have other choice.

Doing it on the device side is much easier than on the router side, as you need to know the MAC Address of the module.  You also need to have a sysop access to the router, which is not always possible.

And when obliged to use static addressing, if there is a conflict with OTA, it's to the user to take care of this.

73 Patrick.
