### ISSUE TITLE
No power ON under batery t-beam 1.2 AXP2101 

### ISSUE THREAD

**Issue by dcardenosa** [richonguzman/LoRa_APRS_Tracker#116]
Hi
I have 2 T-Beams 1.2 with AXP2101 that work ok under usb power but doesn't under battery power. They don´t power up pressing the pwr button. The button works on usb power.  With usb power they measure the battery voltake ok and show (charging) message. If I disconnect the usb cable the t-beam powers off.

With the Meshtastic  fw the batery power works fine on those boards.

I set the environment on vscode to "ttgo-t-beam-v1_2". Cleaned up the vscode environment few times and make a clean git clone of the repository.

Not sure what´s the problem. :S

I also have 2 T-Beams 1.1 that work ok on batery power. 

Thanks 
David EA1FAQ

![imagen](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/170166419/8585978f-7af4-406d-8909-1108cfed5c68)

![imagen](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/170166419/7c2b799c-1173-4ce9-911f-8d3de8fe819c)

**Comment by richonguzman** [comment]
Hi

Sometimes AXP2101 power management chip needs a reboot

Take out the battery and put them back on (without usb)

This may solve this issue

**Comment by dcardenosa** [comment]
Yes!!! The problem was solved! 
Thanks!

David EA1FAQ
