### ISSUE TITLE
Problema Heltec Tracker Lora

### ISSUE THREAD

**Issue by droptic** [richonguzman/LoRa_APRS_Tracker#123]
Al cambiar entre las distintas configuraciónes, el icono que se ve en la pantalla no se refresca y se sobre escribe con el anterior no pudiendo saber claramente cuál configuración está en uso.
Saludos

**Comment by richonguzman** [comment]
si, es una pifia de como funcionan los TFT y la velocidad de refresco, 

no me he metido mas a ellos buscando meterle mejoras a otras cosas :/

**Comment by ON7MHZ** [comment]
Hi , 
might be a stupid question (and maybe not the correct place to ask )  ... but what type of board should I select for the Heltec Tracker at "import arduino project" ? 
I followed the steps as indicated , but uploading the file system failed on my Heltec Tracker with " error code 1 " ... 
Any suggestions ? 
thanks 
Pieter  ( newbie at LoRa APRS ) 
ON7MHZ

**Comment by ON2ON-HAM** [comment]
Pieter,

Als ik je bericht lees 'import arduino project', is mijn eerste vraag, zit je in Visual Code te werken ? Want met die software gaan we de code Builden en Uploaden naar je bordje.

En 2e punt, ging de 'Build' voor je Heltec Wireless Tracker in General en Filesystem goed ?

Grtjs
Luc ON2ON
