### ISSUE TITLE
Heltec Wireless Tracker - code 1 error on upload

### ISSUE THREAD

**Issue by jclifford73** [richonguzman/LoRa_APRS_Tracker#126]
Unable to upload to a Heltec Wireless Tracker board.  This is the error message in VScode terminal:

 *  The terminal process "C:\Users\John\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload', '--environment', 'heltec_wireless_tracker', '--upload-port', 'COM13'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

Using latest firmware & tried 2 tracker boards with the same result.

It looks like it is the same error as experienced by ON7MHZ in Issue #123 

Regards & 73
John GW4BVE

**Comment by richonguzman** [comment]
Hi,

did you pressed buttons like this?
press user button, dont release user button, press reset button, release reset button without releasing user button

Then flash (upload firmware and then filesystem). When it started you can release user button


this is normal task in ESP32S3 sometimes

Please confirm this worked out for you

**Comment by jclifford73** [comment]
Hi Ricardo.   You are a star.   Many thanks, it works perfectly.   I have programmed loads of igates and T-Beams and never had to do that, but all the Heltec tracker boards are the same.
73 John GW4BVE
