### ISSUE TITLE
Heltec Wireless Tracker  >> POWER OFF   Button  ?

### ISSUE THREAD

**Issue by DL4SDR** [richonguzman/LoRa_APRS_Tracker#128]
Hello,
is there any solution possible   powering OFF   a Heltec wireless Tracker....actual only  a message is seen in the Display  when
using Configuration Menue.  Ask because  charging the battery  in ON Mode is  not usefull.
tnx any info
herbert

**Comment by richonguzman** [comment]
Hi Herbert,

as far as I've tested the Heltect Wireless Tracker, if you charge the battery will also power on the board.

powering off (deepSleep) is done by pushing 3 times the user button.

**Comment by DL4SDR** [comment]
Hi Ricardo,
good  to know :-))   mni tnx  agn  for the excellent work you are doing  !
