### ISSUE TITLE
mismatch between json config file and displayed data at aprs.fi

### ISSUE THREAD

**Issue by dg1rue** [richonguzman/LoRa_APRS_Tracker#130]
Hey Richon, thank you so much for your effots in programmin LoRa APRS.
I use TTGO  T22_V1.1 which is recognized by VSC as 1.2
I attach the configuration json file and reception screenshots of aprs.fi
As you can see there is a little difference between config and reception.
May be this information helps you to improve your software.

Hope to hear from you.
best regards and 73s de DG1RUE (aka Holger)
![DG1RUE-7](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/37246956/70fec85e-fc3a-4a11-87b2-7fcb0ff5e562)
![DG1RUE-8](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/37246956/f7d1ac02-9754-4db0-839c-4ce396d6c50e)
![DG1RUE-9](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/37246956/297d8078-a414-4367-860a-3de17e7c8a05)
[tracker_config.json](https://github.com/user-attachments/files/15937485/tracker_config.json)

**Comment by richonguzman** [comment]
All looks good in configuration 

It seems DG1RUE-15 may be joining two packets and this is appearing as faulty comment

Can you update it to my last igate firmware?

**Comment by dg1rue** [comment]
With the last version 21.06. I am stuck in boot loop.
Not familiar with GIT so I chose some of the last branches to bring my baby back on air.

**Comment by richonguzman** [comment]
could we start all over again?

do you have updated the igate?
