### ISSUE TITLE
Symbol is not cleared

### ISSUE THREAD

**Issue by jclifford73** [richonguzman/LoRa_APRS_Tracker#137]
Heltec Tracker Board
Latest firmware

Symbol in top right of the sceen eg car, bike, walker etc is not cleared before writing new symbol on config change with U button.  Results in an illegible symbol.

73 John GW4BVE

**Comment by richonguzman** [comment]
yes, know bug with TFT screens

will try to update it all very soon

**Comment by g3cwi** [comment]
I think these screens support colour too. It would be nice to use that!

**Comment by richonguzman** [comment]
soon will try to play with color, in the meantime , Symbol is cleared as needed
