### ISSUE TITLE
Field length overflow

### ISSUE THREAD

**Issue by g3cwi** [richonguzman/LoRa_APRS_Tracker#139]
The tracker occasionally appends a link to the relevant repo "https://github.com/richonguzman/LoRa_APRS_Tracker 2024.06.21". This rather long field can overflow the info box on APRS.fi. Would it be possible to use a shortened URL?

![image](https://github.com/user-attachments/assets/36738170-0ea6-4f44-8257-9facd3787173)

**Comment by richonguzman** [comment]
like tinyurl?

**Comment by g3cwi** [comment]
That's certainly one possibility!

**Comment by richonguzman** [comment]
im checking new ways to take advantage of the status for the future
