### ISSUE TITLE
Feature request: Real time in received packets logs

### ISSUE THREAD

**Issue by Tapkin12ru** [richonguzman/LoRa_APRS_Tracker#141]
Hello!
Can you add real time settings (use network time for example) and write logs with it?

**Comment by richonguzman** [comment]
Would you please explain each topic with more detail?

**Comment by Tapkin12ru** [comment]
I mean this section here. Currently, the time of the received package is counted from the moment the device is loaded. It would be much more convenient if the records were marked with a real date and local network time (wifi) or GMT time.
![Screenshot_2024-07-20-20-30-38-259_com opera browser-edit](https://github.com/user-attachments/assets/530c9701-26a3-48cf-931f-65a5c12e7308)

**Comment by Tapkin12ru** [comment]
As a local network time, I mean, for example, this setting in the phone
![Screenshot_2024-07-20-20-36-40-520_com android settings-edit](https://github.com/user-attachments/assets/06d62d1d-9032-4127-ab8b-00fb94a24cd7)

**Comment by richonguzman** [comment]
This is a request for the igate firmware then , right?

**Comment by Tapkin12ru** [comment]
Yes, you're right.

**Comment by richonguzman** [comment]
will close it here and try to add NTP server time on igate to solve this
