### ISSUE TITLE
Heltec Wireless Tracker --> BT

### ISSUE THREAD

**Issue by iw9grl** [richonguzman/LoRa_APRS_Tracker#144]
Hello

I'm not able to connect my Heltec Wireless Tracker through BT on my smarpthone .
I enabled it in the settings ( Menú --> Configuration --> BT (ON) ) , but the device is not visible during the BT search .

There is something I forgot or BT is not well supported at the moment ?

thank you
73

**Comment by richonguzman** [comment]
Hi

Heltec Wireless Tracker only has BLE (as all ESP32S3 boards)

**Comment by iw9grl** [comment]
Sorry for question, what does it mean? Is it not possible to connect to Android phones and aprsdroid? Tnx

**Comment by richonguzman** [comment]
Aprsdroid app does not work with BLE connections (not supported).

**Comment by iw9grl** [comment]
Ok tnx 😊
