### ISSUE TITLE
t-beam supreme and huawei p-20

### ISSUE THREAD

**Issue by s51d** [richonguzman/LoRa_APRS_Tracker#145]
I have t-beam supreme 433mhz

I am interested in
Willink - is tray to logging but no success
and
messages on my mobile phone with AprsDroid I dont see board Bluetooth on my phone 

I have an I2C keyboard at home from the adruino uno kit....numbers 0-9 and abcd and #ter*
how can I write messages with it? and how to conect

I have a huawei p20 mobile phone and I don't see lore, is the phone too old?

73 Marko

**Comment by richonguzman** [comment]
> I have t-beam supreme 433mhz
> 
> I am interested in Willink - is tray to logging but no success and messages on my mobile phone with AprsDroid I dont see board Bluetooth on my phone
> 
> I have an I2C keyboard at home from the adruino uno kit....numbers 0-9 and abcd and #ter* how can I write messages with it? and how to conect
> 
> I have a huawei p20 mobile phone and I don't see lore, is the phone too old?
> 
> 73 Marko

Hi Marko,


ESP32S3 (as the ones in T-beam Supreme) only have BLE


so aprsdroid is not supporting phones with BLE

as for the I2C Keyboard: 

I've only tested with M5Stack CARDKB I2C Keyboard , so you would have to check about I2C address of your keyboard to start testing if this would work


on the winlink process, its only by using the tracker with keyboard (for now)
