### ISSUE TITLE
Shutdown through wifi or bluetooth

### ISSUE THREAD

**Issue by iw9grl** [richonguzman/LoRa_APRS_Tracker#147]
Hi

I don't know if it is possible to do, I installed a tbeam in my motorcycle in a very hidden place :)  and I need to shutdown the tbeam board when it 's parked in my own garage ( no GPS available, but I want to save battery charge ) .
Is it possible through bluetooth or wifi, run a shutdown ? I think, could be usefull the possibility to run a local webserver like the iGate ones , to configure all parameters of the tbeam and, why not, have the shutdown button.

thank you
best 73
IW9GRL

**Comment by richonguzman** [comment]
I think on a few solutions:

- web server (more consumption)
- external powerOff button somewhere on the motorbike
- special code to be sended over BT to the tracker?

**Comment by Mane76** [comment]
Maybe oldschool, 

but is there a possibility to get voltage on a motorcycle only when ignition is on (like in cars)?
If yes and when you remove the battery from the tracker it would automatically be turned on and off.

**Comment by iw9grl** [comment]
@Mane76 the idea is to leave battery on the tracker to have it active when motorbike is off (outside home) actually the usb power is under key management, when motorbike is off no power on usb. The problem is, if I leave motorbike in garage (no need to have tracker), the battery discharge and with a new power I don't have enough time to charge it, for example in an half hour (when I move to the office in the morning).
@richonguzman if no other solution is possible I will put an external button to disconnect power (or through some GPIO????) , but the idea to have code over BT could be great!
Tnx
73

**Comment by iw9grl** [comment]
In the meantime I think another solution could be really interesting, I don't know if you already put in place the shutdown after usb power is off ( I see some other requests from other guy), or shutdown after a couple of minutes if no gps fix is available, could be really interesting to wake up the board with a shake sensor connected in some GPIO active only during the deep sleep (that connect gnd or vdd to a GPIO pin), enable or not through the configuration file, in this way we don't need any other external switch :) is it a crazy request?? 😂😂

**Comment by richonguzman** [comment]
> is it a crazy request?? 😂😂

yes it is! hahahaha

but will see what I can do as this is a very specific situation to solve

**Comment by iw9grl** [comment]
The only things I need just for summary, is to poweroff board remotely if tracker is not accessible where installed

**Comment by richonguzman** [comment]
> The only things I need just for summary, is to poweroff board remotely if tracker is not accessible where installed

like receiving a special message over aprs? 

because BT does not have much range for remote turning it of

**Comment by iw9grl** [comment]
I need to turn off very close to the tracker

**Comment by richonguzman** [comment]
not a clean solution for now, but I dream on building an app that controls Tracker from phone
