### ISSUE TITLE
Heltec Board V3

### ISSUE THREAD

**Issue by DM4JH** [richonguzman/LoRa_APRS_Tracker#150]
I have problems to upload to the board. What I have to choose in the platformio as env?
73 Jens DM4JH

**Comment by richonguzman** [comment]
Hi Jens,

lets start with a few question:

1) what boards is this? (to be super sure about the exact model/brand/model)
2) did you follow the wiki guide ?

**Comment by richonguzman** [comment]
soon will be WebFlasher which will solve all VSCODE issues, wait a day and it will be available
