### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by g3cwi** [richonguzman/LoRa_APRS_Tracker#151]
I use BLE with my trackers (several). Instead of the tracker identifying with a number, it would be useful if identified with the callsign+SSID.

**Comment by richonguzman** [comment]
as you can change the callsign during use, but bluetooth is only initialized at boot up once , this was the reason for using this numbers (which are MAC address numbers)

**Comment by richonguzman** [comment]
added into new release with webflasher config ;)
