### ISSUE TITLE
Reading an external voltage Heltec WiFi LoRa 32 V3

### ISSUE THREAD

**Issue by g3cwi** [richonguzman/LoRa_APRS_Tracker#154]
I am trying to read an external battery voltage. The web interface refers to pin 34. I assumed this might mean GPIO 34 (pin 11 on the Heltec Wifi LoRa V3). However, this does not appear to be the correct pin. on this board. Any suggestions?

**Comment by richonguzman** [comment]
you can use any unused pin for external voltage measurement.

i dont have all the pins in my head to recommend you one, the pin34 was just for lora32v2.1 board and you can use anyone you find free and it should work

compare the pinouts used with the available for each board (condering not using gps, lora, oled pins of the board)

**Comment by g3cwi** [comment]
I tried GPIO 46 (board pin 5). That appears to be unassigned. No luck. I just get a constant Voltage reported that it not related to the actual voltage on the pin. I can change the reported values by changing the resistor values in the web interface but the reported voltage is not related to the actual applied voltage. I tried changing the actual applied volt (1.37-2.84 volts) but the reported voltage remains unchanged at 3.84 Volts. I rebooted after the changes in case it was only sampled infrequently but no change. 

This would be a useful facility as my solar digi runs the board off a 5 Volt USB supply so I need to be able to monitor the batteries directly to understand their state of charge. Thanks.

**Comment by richonguzman** [comment]
wait!

this pin recommendation is for igate firmware, not for tracker...   so I would need to generate code for external voltage measurement (outside the one from the internal battery readings)

**Comment by g3cwi** [comment]
This is on an iGate - not a tracker. Woops I have put the problem in the wrong section. Sorry. If you can delete it or close it here I will open it in the igate section.

**Comment by g3cwi** [comment]
Moved to igate section.
