### ISSUE TITLE
“bluetoothType”: 1 not working on heltec wireless tracker

### ISSUE THREAD

**Issue by 9M2PJU** [richonguzman/LoRa_APRS_Tracker#155]
rebuilding and reflashing few times and it did not showing up. “bluetoothType”: 0 is up but I dont have iPhone to test.

**Comment by richonguzman** [comment]
> rebuilding and reflashing few times and it did not showing up. “bluetoothType”: 0 is up but I dont have iPhone to test.

as per WIKI info:
"bluetoothType":1 is for Android and BT classic

all ESP32S3 based boards have BLE (so "bluetoothType":0 (for iPhone + aprs.fi) or "bluetoothType":2 for Android and BLE Terminal for testing right now))

**Comment by 9M2PJU** [comment]
> > rebuilding and reflashing few times and it did not showing up. “bluetoothType”: 0 is up but I dont have iPhone to test.
> 
> as per WIKI info: "bluetoothType":1 is for Android and BT classic
> 
> all ESP32S3 based boards have BLE (so "bluetoothType":0 (for iPhone + aprs.fi) or "bluetoothType":2 for Android and BLE Terminal for testing right now))

Thanks, I will try type 2 and wiki should include type 2 too.

**Comment by richonguzman** [comment]
> > > rebuilding and reflashing few times and it did not showing up. “bluetoothType”: 0 is up but I dont have iPhone to test.
> > 
> > 
> > as per WIKI info: "bluetoothType":1 is for Android and BT classic
> > all ESP32S3 based boards have BLE (so "bluetoothType":0 (for iPhone + aprs.fi) or "bluetoothType":2 for Android and BLE Terminal for testing right now))
> 
> Thanks, I will try type 2 and wiki should include type 2 too.

it will once we know of an app to make this work as it should

**Comment by 9M2PJU** [comment]
![image](https://github.com/user-attachments/assets/09cd9243-1dba-4c10-a924-70c3e8c28438)

Yes, maybe APRSDroid developer should notice.

Thanks again.

**Comment by richonguzman** [comment]
> ![image](https://private-user-images.githubusercontent.com/991353/366953966-09cd9243-1dba-4c10-a924-70c3e8c28438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTYwODUsIm5iZiI6MTcyNjE1NTc4NSwicGF0aCI6Ii85OTEzNTMvMzY2OTUzOTY2LTA5Y2Q5MjQzLTFkYmEtNGMxMC1hOTI0LTcwYzNlOGMyODQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNTQzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzEzNDM3N2MwNzdiODY3NWY5YWE1NmJiZjk4YTZmYmU3NmExYmI3OTIyMWYxNDIxYzkzZmEwNjNkMTQ1MzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qH10YBr6y2FZJB_FLowndKznFYNrSMzuwe5hi78gqTI)
> 
> Yes, maybe APRSDroid developer should notice.
> 
> Thanks again.

they already know:

there is no BLE serial packet format defined, this is why they dont have a BLE available version (for now)
