### ISSUE TITLE
WifiAP - Web Configuration

### ISSUE THREAD

**Issue by iw9grl** [richonguzman/LoRa_APRS_Tracker#159]
Hi Ricardo

I tried the Web configuration of the board ( Heltec WT )  and it works , but I'm not able to exit from WifiAP, tracker usage doesn't start

there are some particular sequences of buttons to exit from WifiAP ?

thank you
73

**Comment by richonguzman** [comment]
when you save it should reboot and go right into Tracker mode, unless some data saved is not compatible with this.

any special icon symbol character used?

**Comment by iw9grl** [comment]
Hi Ricardo

the icons used are man, car and motorbike \> not any other special symbols .

Another strange behaviour I noticed in Heltec WT, many times the board goes in boot loop, this not happens with previous firmware I used, if I remember well the ones at the end of August

73

**Comment by richonguzman** [comment]
i will close this as new webflasher has many corrections

if you find anything let me know in detail in another"issue" please

**Comment by iw9grl** [comment]
Sure, thank you
