### ISSUE TITLE
support for ttgo-t-beam-AXP2101-v1_2

### ISSUE THREAD

**Issue by ch0mik** [richonguzman/LoRa_APRS_Tracker#161]
plase add support for board ttgo-t-beam-AXP2101-v1_2

**Comment by richonguzman** [comment]
for more than a year the board has been supported as: ttgo-t-beam-v1_2

**Comment by ch0mik** [comment]
2023.07.01 Added Support for new T-Beam AXP2101 v1.2 Board.

@richonguzman  i cant see it on boards 
![2024-10-03 18_51_16-Window](https://github.com/user-attachments/assets/b4be8617-60ff-4047-863d-a766ba0c8409)

**Comment by ch0mik** [comment]
ok,

i see it now : just ttgo-t-beam-v1_2

[env:ttgo-t-beam-v1_2]
extends = env:esp32
board = ttgo-t-beam
build_flags =
	-Werror -Wall
	-DTTGO_T_Beam_V1_2
	-DHAS_SX1278
	-DHAS_AXP2101
	-DHAS_BT_CLASSIC
	-DHAS_GPS_CTRL
lib_deps =
	${common.lib_deps}
	lewisxhe/XPowersLib @ 0.2.4
	adafruit/Adafruit GFX Library @ 1.11.9
	adafruit/Adafruit SSD1306 @ 2.5.10
	adafruit/Adafruit SH110X @ 2.1.10

**Comment by richonguzman** [comment]
yes!
