### ISSUE TITLE
Web-Config

### ISSUE THREAD

**Issue by 2e0wkw** [richonguzman/LoRa_APRS_Tracker#164]
How do you re-enter the web-config after the initial configuration.

The board seemed to take some of my config detail and then restarted before i pressed save and now i can't re-enter unless i re-load the f.w.

TTGO-Lora32 V2 using Chrome on a Mac

Thanks
Eric

**Comment by richonguzman** [comment]
hi Eric

https://github.com/richonguzman/LoRa_APRS_Tracker/wiki/01.-Installation-Guide-%23-Guia-de-Instalacion

the first part will help you

TLDR:

triple push of the user button ;)
