### ISSUE TITLE
Access Point breakdown V0.9.8

### ISSUE THREAD

**Issue by M0IGA** [richonguzman/LoRa_APRS_Tracker#165]
In new firmware with a web configurator, AP doesn't start after save config and rebooting.
Tracker works fine if all parameters were set correctly, but no more AP
Tested on T-Beam v1.2 and ESP32 Wemos lite + E220.

**Comment by richonguzman** [comment]
Great then, it was coded this way. Who needs Wifi for regular Tracker use? (besides using it on the car with no problem of power supply?)

**Comment by richonguzman** [comment]
does this E220 use LLCC68 ?

**Comment by M0IGA** [comment]
> Great then, it was coded this way. Who needs Wifi for regular Tracker use? (besides using it on the car with no problem of power supply?)

Ok, if there is a feature, issue could be closed.
Consider adding an info about it, because I pressed save and have to flash it again. I think it could be helpful for many of us, to avoid mistakes.

**Comment by M0IGA** [comment]
> does this E220 use LLCC68 ?

Yes it has.

**Comment by richonguzman** [comment]
> > does this E220 use LLCC68 ?
> 
> Yes it has.

can you confirm que correct pinout selection of the trackers for it then?

**Comment by richonguzman** [comment]
> > Great then, it was coded this way. Who needs Wifi for regular Tracker use? (besides using it on the car with no problem of power supply?)
> 
> Ok, if there is a feature, issue could be closed. Consider adding an info about it, because I pressed save and have to flash it again. I think it could be helpful for many of us, to avoid mistakes.

sure thing, I'm writing the WIKI right now with the details to get it more easy

PS: if you need to flash again , just press 3 times and in the menu select Wifi AP again and it will start all over again
