### ISSUE TITLE
Restart without AP signal

### ISSUE THREAD

**Issue by BH9FPF** [richonguzman/LoRa_APRS_Tracker#168]
Hello blogger, after flashing the program through the web page. After restarting the device, the AP signal cannot be searched. Can it be fixed in the next version? Have you also considered defining a button function that can be used to switch pages. My device is ttgo-lora32 2.1

**Comment by richonguzman** [comment]
The normal behavior is that WifiAP is stopped after webConfiguration is saved and Tracker restarts. As I see the Lora32 v2.1 boards needs a button to access the WifiAP configuration again. Should I add a button in firmware for you to add it as a DIY solution?

**Comment by BH9FPF** [comment]
I personally hope that the WifiAP signal remains searchable at all times, making it convenient to adjust configuration information. By adding a button, I mean enabling users to flip through pages and view OLED display information. Of course, these are all my personal suggestions, and the specific implementation still requires comprehensive consideration of the opinions of your other friends.

**Comment by S57PNX** [comment]
WifiAP signal doubles the power consumption, so by having it available all the time you reduce the battery autonomy in half. This is not a good design decision.

**Comment by richonguzman** [comment]
> WifiAP signal doubles the power consumption, so by having it available all the time you reduce the battery autonomy in half. This is not a good design decision.

this is why I make WiFiAP available only when configuration is needed:
150mA with WiFiAP vs 60-80mA for tracker normal mode.

**Comment by S57PNX** [comment]
Yes, my comment was addressed to BH9FPF who requested to have WifiAP available all the time, which is not a good idea.

**Comment by richonguzman** [comment]
Now WiFiAP will stop after 1 min of no client connected to the WifiAP

- so if started by error, it will return to normal in 1 min.
- if started and you dont have any pc o phone to press "save" button it will still return to normal Tracker mode after 1 min

**Comment by richonguzman** [comment]
this is added to V2.0.1 in WebInstaller

**Comment by BH9FPF** [comment]
You're amazing. I greatly admire your technical level. I want to learn more from you.





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "richonguzman/LoRa_APRS_Tracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月10日(星期四) 晚上9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [richonguzman/LoRa_APRS_Tracker] Restart without AP signal (Issue #168)





 
Now WiFiAP will stop after 1 min of no client connected to the WifiAP
  
so if started by error, it will return to normal in 1 min.
 
if started and you dont have any pc o phone to press "save" button it will still return to normal Tracker mode after 1 min

**Comment by Vic152** [comment]
Call me stupid guys but where is user button on Liligo TDeck?

**Comment by richonguzman** [comment]
USER button is the boot but I forgot to add this as a valid user button, will fix it very soon

**Comment by Vic152** [comment]
> USER button is the boot but I forgot to add this as a valid user button, will fix it very soon

so does this mean I have to flip 2 position switch on TDeck very fast 3 times?

**Comment by richonguzman** [comment]
> > USER button is the boot but I forgot to add this as a valid user button, will fix it very soon
> 
> so does this mean I have to flip 2 position switch on TDeck very fast 3 times?

no.

i dont know what leads you to this conclusion, but no, sorry: the user button does not work as it should on T-deck (tomorrow I will try to add it)
