### ISSUE TITLE
Telemetry value of Voltage and Current

### ISSUE THREAD

**Issue by iw2ejh** [richonguzman/LoRa_APRS_Tracker#169]
Hi, In the latest version with the ability to transmit the voltage value in Telemetry format, using the TTGO TBEAM V1, I lost the possibility to monitor the current consumption
Is there a way to get it again?
Thanks
![Tracker_TTGO_TBeam_V1_Voltage_Current](https://github.com/user-attachments/assets/47ecf842-1bc7-4b4f-b379-6102f0ba2598)

**Comment by richonguzman** [comment]
I guess there is a way to still send it, but is it really needed?

I guess for initial or testing purposes it was useful but for long periods of sending data , current does not change that much over time right?

**Comment by iw2ejh** [comment]
just had a case where an Igate randomly hangs, and after we bring it down to the lab, we observed that randomly the current run to 400mA  and it start to overheat and then hang. Having the current value available we would have avoided various onsite for reset/restart as we may have understood earlier it has a problem.   But at the end up to you if adding it or not to the available telemetry data.

**Comment by richonguzman** [comment]
but you mention IGATE consumption ?

**Comment by iw2ejh** [comment]
yes, that example was a recent case on an Igate,   but similar problem may also occurs on a tracker.

**Comment by richonguzman** [comment]
> yes, that example was a recent case on an Igate, but similar problem may also occurs on a tracker.

the thing is, only 1 type of board has current (t-beam v1) no other has a power managment chip
