### ISSUE TITLE
tracker shut down

### ISSUE THREAD

**Issue by iw2ejh** [richonguzman/LoRa_APRS_Tracker#17]
Would it  be possible to shut down the tracker when the integrated lithium battery level goes under a certain level in order to avoid overdischarge the battery ?
thanks
Marino - iw2ejh

**Comment by richonguzman** [comment]
Hi, the tracker has a power management chip that already does this ... when it reaches certain voltage the tracker shut itself off.

Do you need a special defined voltage as the lowest you want from your battery?

**Comment by iw2ejh** [comment]
I did a test and the tracker power down when the voltage drop under 3 Volts. So the tracker power management is doing his job. So it should be ok for me. Thanks.
