### ISSUE TITLE
Heltec Wireless Tracker looping on startup 

### ISSUE THREAD

**Issue by pdevlin13** [richonguzman/LoRa_APRS_Tracker#171]
Hi Ricardo
As discussed on the SOTA forum, I have opened the looping as an issue, so that I can share the attached video of the looping. The video only show one loop but it will continue looping for up to 2 minutes before stabilising. It will randomly startup without any issue.

I have just noticed on the loop the second time 202 appears in place of the version, just an observation.

I have iPhone BLE enabled, I think someone suggested it only happened in this Bluetooth mode but I haven’t tried other BT configs yet.
Happy to do any testing 

Paul MW0PDV 

https://github.com/user-attachments/assets/56958d9e-1829-44e3-a0dd-dfae75e9fccd

**Comment by richonguzman** [comment]
Great let's find out what's going on with this:

1) let's try it with latest firmware 2.0.2 please
2) change only the callsigns and nothing else on the webUI 
3) select on tracker menu the freq you need (third one I assume) this will be saved on the internal memory and will start with it all the next times it boots

**Comment by pdevlin13** [comment]
ok, fresh install as below, tracker starts up fine.
Reflash and enable iPhone BLE tracker starts looping.


> Great let's find out what's going on with this:
> 
> 1. let's try it with latest firmware 2.0.2 please
> 2. change only the callsigns and nothing else on the webUI
> 3. select on tracker menu the freq you need (third one I assume) this will be saved on the internal memory and will start with it all the next times it boots

**Comment by richonguzman** [comment]
did you change the frequency at all? anything besides only CALLSIGN?

is the callsign saved with any "white/black" space behind the SSID?

**Comment by pdevlin13** [comment]
I only changed callsign, and this works no looping.
If I only change callsign and enable iphone BLE it starts looping.

I am trying to do some crude diagnostics, and so far established it returns from the POWER_Utils::batteryManager() call at line 170ish in  Lora_APRS_Tracker_main before looping. 
<img width="494" alt="Screenshot 2024-10-12 151444" src="https://github.com/user-attachments/assets/13f03a78-dc6b-4bdd-9cac-4a7d112d35ef">

**Comment by pdevlin13** [comment]
The terminal output from the testing mentioned above
<img width="416" alt="Screenshot 2024-10-12 152006" src="https://github.com/user-attachments/assets/387a51e9-e2cf-493f-9174-b0807ff7ccdd">

**Comment by richonguzman** [comment]
so is this inside "obtainBatteryInfo()" ???

which board have you? V1 or V1.1?

**Comment by pdevlin13** [comment]
> so is this inside "obtainBatteryInfo()" ???

No its inside BatteryManager

<img width="704" alt="Screenshot 2024-10-12 152951" src="https://github.com/user-attachments/assets/6a4ac301-8ba6-438c-8793-1266b50d90f6">

I will check version, just neet to open the enclosure.

**Comment by richonguzman** [comment]
> > so is this inside "obtainBatteryInfo()" ???
> 
> No its inside BatteryManager
> 
> <img alt="Screenshot 2024-10-12 152951" width="704" src="https://private-user-images.githubusercontent.com/37481249/375964637-6a4ac301-8ba6-438c-8793-1266b50d90f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDM5MDIsIm5iZiI6MTcyODc0MzYwMiwicGF0aCI6Ii8zNzQ4MTI0OS8zNzU5NjQ2MzctNmE0YWMzMDEtOGJhNi00MzhjLTg3OTMtMTI2NmI1MGQ5MGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDE0MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMTYyYTJiYTY3Y2E5ZDdhOWRmNzc2ZmFiYTU0YjFhNDg2N2E0ZGM0NTRiZDJkZmFhMmRlZjYxNGE3NDk5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wvklehQweIToqN3jg9KuBIBfBuI-R1H7SB9PQ77G3x0">
> I will check version, just neet to open the enclosure.

yes, but "obtainBatteryInfo()" is the one called there... so it needs to check inside it to know what is not being right

it checks board has ADC_CTRL (which heltecs do have) and also BATTERY_PIN

**Comment by pdevlin13** [comment]
Oh yes sorry just notice the call in the if statement.
My version is  1.1

**Comment by pdevlin13** [comment]
Ok, this is a bit strange, for each loop  it always seems completes the setup() function but only sometimes gets as far a calling  POWER_Utils::batteryManager()  Until it eventually  it starts up.
Hope this helps :-)

Paul

**Comment by richonguzman** [comment]
will have to change the way this is checked then, give me a few days to get with a test code

**Comment by pdevlin13** [comment]
Hi Ricardo
I have done some more digging today as the previous testing seemed to produce random results.
It appears to be the pAdvertising->start() call, in BLE_Utils that is causing the Heltec to loop. If I put a sleep 20 after this call it still cycles instantly. Commenting this line out also stops it cycling.

<img width="1037" alt="Screenshot 2024-10-13 130106" src="https://github.com/user-attachments/assets/ec72cc1d-45bb-48c4-b3d5-fd31b335c409">

**Comment by richonguzman** [comment]
Hardware test !!!! 

add a 100uF /16V between pin 5 (3.3v) and 4 (GND) as it seems on some trackers the voltage at boot is dropping a small amount of time not allowing full boot process

**Comment by pdevlin13** [comment]
> Hardware test !!!!
> 
> add a 100uF /16V between pin 5 (3.3v) and 4 (GND) as it seems on some trackers the voltage at boot is dropping a small amount of time not allowing full boot process

I will give it a try tomorrow 
Thanks

**Comment by pdevlin13** [comment]
Hi Ricardo, as in SOTA reflector this does seem to be the solution. I happy to close the issue 😀
Thanks
Paul MW0PDV

**Comment by richonguzman** [comment]
for all who will look a this in the future:

HELTEC WIRELESS TRACKER: add 100uF /16V electrolytic capacitor between pin 5 (+) and 4 (- GND) to solve random reboots.
