### ISSUE TITLE
Empty comment field when in route.

### ISSUE THREAD

**Issue by gbecki** [richonguzman/LoRa_APRS_Tracker#2]
Hello,
The comment field in the compressed format is sended empty when in route, but its ok when the Tracker boots ("defaultStatusAfterBoot" : true,), so it's never updated again after boot.

>>> aprslib.parse("PU5KNB-12>APLR01,WIDE1-1,qAO,PP5AMP-10:!/\AutB7K->!!Q")
{'raw': 'PU5KNB-12>APLR01,WIDE1-1,qAO,PP5AMP-10:!/\\AutB7K->!!Q', 'from': 'PU5KNB-12', 'to': 'APLR01', 'path': ['WIDE1-1', 'qAO', 'PP5AMP-10'], 'via': 'PP5AMP-10', 'messagecapable': False, 'format': 'compressed', 'altitude': 0.3048, 'symbol': '>', 'symbol_table': '/', 'latitude': -27.43332825798187, 'longitude': -48.45813097557007, 'comment': ''}

https://aprs.fi/?c=raw&call=PU5KNB-12

Ps: Keep the awsome job.
Kind Regards,

Guilherme - PU5KNB
QEX Team.

**Comment by richonguzman** [comment]
Fixed Guilherme!!! THANKS

let me know if you test it

obrigado!!!

**Comment by gbecki** [comment]
Hola Ricardo!!

Comment field working as expected now!

Gracias!!!

73, Guilherme
