### ISSUE TITLE
Power on the T-Beam v1.2 with GPIO Pin on battery mode

### ISSUE THREAD

**Issue by TF1987** [richonguzman/LoRa_APRS_Tracker#20]
Hi, is there any chance to use a free IO-Port to power on/off the board (Lilygo T-Beam v1.2 with AXP2101)?

I'd like to use other buttons in a housing. 

73 de Thomas, DO4FT

**Comment by richonguzman** [comment]
I did not find any data sheet to know which pin it was... can you help me find the pin or button number in T-beam to do this as an external button ?

**Comment by richonguzman** [comment]
you can redefine a pin to add it as a button replacing the internal pin38 which is the central button (which could be pressed 3 short times to shutdown any T-beam
