### ISSUE TITLE
Issue whith Lilygo T-Beam v1.2 with AXP2101

### ISSUE THREAD

**Issue by HJ5JMS** [richonguzman/LoRa_APRS_Tracker#23]
Hello !

I recently received a Lilygo T-Beam v1.2 with AXP2101 from Aliexpres, but after installing the tracking software, the device doesn't work and seems to be related to the APX210.

The main screen shows battery: -0.00v and the device got stuck when preparing to transmit. Checking the serial monitor, I also found that there is an error message during boot: [ERROR] [AXP192] Boot failed!

Is there a way to handle this problem, or is the hardware definitely not supported yet?

![image](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/142853794/6a192c3d-252e-4824-b552-6c46bb8dd765)
![PXL_20230822_005355260](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/142853794/a8816fc3-5a1b-4f94-9b94-27ba30521382)

Thank you!!

**Comment by richonguzman** [comment]
hi , as you have noticed you need to use the "env:ttgo-t-beam-v1_2" 

this will enable the use of the AXP2101 power management chip and your Tracker should work fine now?

**Comment by HJ5JMS** [comment]
Hello !

You're right, I was overlooking some important env - related steps in the flashing process.

Thank you!
