### ISSUE TITLE
GPS send null position

### ISSUE THREAD

**Issue by iw2ejh** [richonguzman/LoRa_APRS_Tracker#25]
![20230825_131243](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/17383176/b667f6cf-2944-4676-96d1-2bf73a29dbed)
I was in version 2023-7-13 and everything in the tracker was working as expected
I updated to version 2023-8-24
with that version, (after the GPS acquire the position, led blinking) the tracker send out a packet with null position.2023-08-25 12:59:39 CEST: [IW2EJH-5](https://aprs.fi/?c=raw&limit=&call=IW2EJH-5)>APLRT1,WIDE1-1,qAR,[iw2ejh-11](https://aprs.fi/?c=raw&limit=&call=iw2ejh-11):>https://github.com/richonguzman/LoRa_APRS_Tracker 2023.08.19
   type: status
   srccallsign: IW2EJH-5
   dstcallsign: APLRT1
   status: https://github.com/richonguzman/LoRa_APRS_Tracker 2023.08.19

2023-08-25 13:02:35 CEST: [IW2EJH-5](https://aprs.fi/?c=raw&limit=&call=IW2EJH-5)>APLRT1,WIDE1-1,qAR,[iw2ejh-11](https://aprs.fi/?c=raw&limit=&call=iw2ejh-11):!null7?TWQ$XR[E8Q Bat=4.20V (87mA) [Invalid packet]
   type: location
   srccallsign: IW2EJH-5
   dstcallsign: APLRT1
   messaging: 0

while with the previous FW, the packet looks like:
2023-08-25 12:46:13 CEST: [IW2EJH-5](https://aprs.fi/?c=raw&limit=&call=IW2EJH-5)>APLRT1,WIDE1-1,qAR,[iw2ejh-11](https://aprs.fi/?c=raw&limit=&call=iw2ejh-11):!/7?UVQ$Xo[EIQ Bat=4.12V (-90mA)
   type: location
   format: compressed
   srccallsign: IW2EJH-5
   dstcallsign: APLRT1
   latitude: 45.813525461638 °
   longitude: 10.070165858986 °
   altitude: 229.81562896278 m
   symboltable: /
   symbolcode: [
   messaging: 0
   posresolution: 0.291 m
   comment: Bat=4.12V (-90mA)

I rolled back to that version and it work fine, I put again the new version and got the same behaviour.

additional info:  on the display the gps the lat and long are correctly displayed

**Comment by richonguzman** [comment]
Hi,

can you tell me which board are you using? 

my last firmware available for the Tracker is 2023.08.19 so this is strange

**Comment by iw2ejh** [comment]
ops sorry, yes version is 2013-8-19,  i named the directory with the date I download the fw.  
The board is 'ttgo-t-beam-v1'  and fw is 2023-08-19

**Comment by richonguzman** [comment]
could it be you flashed another filesystem? or changed something when uploading the new firmware?

which version was the "before" version which has no flaws for you?

**Comment by iw2ejh** [comment]
version 2023-7-13  was the version I then updated to 2023-8-19 and the formed packet did not show the gps position.  I then rolled back to version 2023-07-13 and the gps position in the packet was correct.
I then updated again to 2023-08-19 and got again the null? in the packet sent 
you can see the trace in aprs.fi:  https://aprs.fi/?c=raw&call=IW2EJH-5   

Only thing i can have touched is the config file, i cup/paste the first part, I will try to reload with the original  and run a new test.

**Comment by richonguzman** [comment]
Please update also the filesystem with the new data (not pasting the old) as new features has been added and this may be causing the problem

**Comment by iw2ejh** [comment]
I unzipped the FW in a new directory and changed manually the value in the tracker.config file, compiled,uploaded and uploaded filesystem, and now it work fine. 
here is a extract of the syslog showing when the gps data was not sent correctly and after with the correct value:
Aug 25 16:25:32	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - GPS - IW2EJH-5 / APLRT1 / WIDE1-1 / -74dBm / 10.00dB / 1573Hz / 0.00N / 0.00E / 5191.6km
Aug 25 16:27:35	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - GPS - IW2EJH-5 / APLRT1 / WIDE1-1 / -70dBm / 9.50dB / 1636Hz / 0.00N / 0.00E / 5191.6km
Aug 25 16:29:38	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - GPS - IW2EJH-5 / APLRT1 / WIDE1-1 / -71dBm / 10.00dB / 1716Hz / 0.00N / 0.00E / 5191.6km
Aug 25 16:31:50	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - GPS - IW2EJH-5 / APLRT1 / WIDE1-1 / -71dBm / 10.50dB / 1745Hz / 0.00N / 0.00E / 5191.6km
Aug 25 16:33:55	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - GPS - IW2EJH-5 / APLRT1 / WIDE1-1 / -71dBm / 9.00dB / 1685Hz / 0.00N / 0.00E / 5191.6km
Aug 25 16:34:01	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - <ÿIW2EJH-5>APLRT1,WIDE1-1:>https://github.com/richonguzman/LoRa_APRS_Tracker 2023.08.19
Aug 25 16:37:16	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - GPS - IW2EJH-5 / APLRT1 / WIDE1-1 / -72dBm / 9.25dB / 1627Hz / 45.81N / 10.07E / 1.3km
Aug 25 16:37:23	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - <ÿIW2EJH-5>APLRT1,WIDE1-1:>https://github.com/richonguzman/LoRa_APRS_Tracker 2023.08.19
Aug 25 16:52:19	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - GPS - IW2EJH-5 / APLRT1 / WIDE1-1 / -73dBm / 10.50dB / 1673Hz / 45.81N / 10.07E / 1.3km
Aug 25 16:56:13	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - GPS - IW2EJH-5 / APLRT1 / WIDE1-1 / -73dBm / 10.75dB / 1592Hz / 45.81N / 10.07E / 1.2km
Aug 25 16:56:19	192.168.1.72	ESP32 LoRa [APRS] - iw2ejh-11 - LoRa Rx - <ÿIW2EJH-5>APLRT1,WIDE1-1:>https://github.com/richonguzman/LoRa_APRS_Tracker 2023.08.19
-------------------------------------------------------------------------

still have a small glitch, but do not know when it appear because usually I do not keep the lcd display connected :  the date and time is correct  but the year/month/day is showing 1999-12-31 .  is this something known or is is still an error in my config?

**Comment by iw2ejh** [comment]
![20230825_163850](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/17383176/8096ced8-ce09-425b-8624-125d16b9800e)

**Comment by richonguzman** [comment]
Maybe wait a little longer and tell me about it later.

Usually the time is the first to be received , then the date and finally the gps fix (and position)

**Comment by richonguzman** [comment]
did it got resolved?

**Comment by iw2ejh** [comment]
The "null?" packet sent out to aprs in the packet string is solved.  The date  displayed on the Oled is still at 1999-12-31. This is not important at the moment, I will program a new board for a friend tomorow and check if it work. I will update when test done.
