### ISSUE TITLE
Button OFF  Function ?

### ISSUE THREAD

**Issue by DL4SDR** [richonguzman/LoRa_APRS_Tracker#28]
If possible  in one of the next updates: Please an Option to Disable  BUTTON Function  due to use it only in one Mode

**Comment by richonguzman** [comment]
Hello

Do you mean disable all buttons or just disable middle button?

**Comment by DL4SDR** [comment]
Hi Ricardo, Middle Button.Aktuell testing dk4sdr-7...See aprs.fi73HerbertAm 04.09.2023 14:24 schrieb "Ricardo Guzman (Richonguzman)" ***@***.***>:
Hello
Do you mean disable all buttons or just disable middle button?

**Comment by richonguzman** [comment]
Ok

But now you should explain me what should the middle button do : only TX? Or change callsigns? Or just to block menu options?

**Comment by DL4SDR** [comment]
Hello Ricardo

 

>>> Or change callsigns

 

a friend of mine has some difficulties to use his Finger's (diabetic polyneuropathia) AND  he take the Tracker in his Jacket  Or  basket

 

hope it is makeable

 

73's

Herbert

 

 

 

 

Von: Ricardo Guzman (Richonguzman) ***@***.*** 
Gesendet: Montag, 4. September 2023 15:05
An: richonguzman/LoRa_APRS_Tracker ***@***.***>
Cc: DL4SDR ***@***.***>; Author ***@***.***>
Betreff: Re: [richonguzman/LoRa_APRS_Tracker] Button OFF Function ? (Issue #28)

 

Ok

But now you should explain me what should the middle button do : only TX? Or change callsigns? Or just to block menu options?

**Comment by richonguzman** [comment]
So he only need to disable middle button completely to avoid pressing it on the bag , right?

**Comment by DL4SDR** [comment]
YES :-)

 

 

Von: Ricardo Guzman (Richonguzman) ***@***.*** 
Gesendet: Montag, 4. September 2023 21:11
An: richonguzman/LoRa_APRS_Tracker ***@***.***>
Cc: DL4SDR ***@***.***>; Author ***@***.***>
Betreff: Re: [richonguzman/LoRa_APRS_Tracker] Button OFF Function ? (Issue #28)

 

So he only need to disable middle button completely to avoid pressing it on the bag , right?

**Comment by richonguzman** [comment]
Please mail me to show you what to change in the code for this custom version ;)
