### ISSUE TITLE
How  connect  bme280 modul 

### ISSUE THREAD

**Issue by radioman1511** [richonguzman/LoRa_APRS_Tracker#29]
How connected bme280 modul to t-beam v1.1 or 1.2.
Grts  Radioman

**Comment by richonguzman** [comment]
Hi "Radioman"

BME280 should be connected as any I2C module (parallel to the OLED SCREEN)

VCC to 3.3V
SDA to SDA
SCL to SCL
GND to GND

**Comment by radioman1511** [comment]
thanks for info
