### ISSUE TITLE
Tracker travado na tela TX

### ISSUE THREAD

**Issue by px5e9142** [richonguzman/LoRa_APRS_Tracker#3]
Holla!

Estou usando seu código num T-Beam versão 1.2 e ele trava na tela TX. No terminal aparece erro ao inicializar o controlador de carga AXP192 que no meu T-Beam é outro, AXP2101.

Gracias.

Antonio 
![IMG-20230611-WA0008](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/52507439/f6c8f4dd-d000-445e-9244-3246eeaf2c15)

![IMG-20230611-WA0006](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/52507439/d23f6dc5-7ddf-4b86-96ec-3f05d44a92c2)

![IMG_20230610_193212](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/52507439/217616d8-adc2-4514-8197-46617ccc59c1)
![IMG_20230610_191626](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/52507439/bc48f742-7abf-40a1-8130-87aabfa99edc)
![IMG_20230610_191659](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/52507439/b4b19fb9-7a8b-4fd5-903d-02d07110cc01)
![IMG-20230611-WA0010](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/52507439/cedd44ba-b86a-49bb-a749-cf895b7ea0ec)

**Comment by richonguzman** [comment]
Olá, não encontrei informações sobre sua placa v1.2, você poderia colocar um link para analisá-la?

Parece que é muito novo, qual chip LoRA ele usa?

**Comment by Mateus-PP5FMM** [comment]
The LoRa chip is the same, only the power management chip has been changed to the AXP2101.
The purchase was made at Lilygo's own store on Aliexpress.
I believe this version of the board (V1.2 2023-05-08) is being sold as of now.

Information about T-Beam V1.2 schematic and new chip AXP2101:

https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/schematic/LilyGo_TBeam_V1.2.pdf

https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/lib/XPowersLib

**Comment by richonguzman** [comment]
Will have to look at it for testing , Sadly i dont have this board here to further testing (so this could be a little slower)

Saludos,

Ricardo / Richon
(Enviado desde mi celular a tubos)

El 13-06-2023, a las 08:10, Mateus PP5FMM ***@***.***> escribió:

﻿

The LoRa chip is the same, only the power management chip has been changed to the AXP2101.
The purchase was made at Lilygo's own store on Aliexpress.
I believe this version of the board (V1.2 2023-05-08) is being sold as of now.

Information about T-Beam V1.2 schematic and new chip AXP2101:

https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/schematic/LilyGo_TBeam_V1.2.pdf

https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/lib/XPowersLib

**Comment by Mateus-PP5FMM** [comment]
Ok ricardo,
Quien tiene esta placa v1.2 es Antonio (PU5PWM) que escribió antes. Lo estaba ayudando a instalar Tracker y luego descubrimos que la versión de la placa que había comprado era nueva y con el chip AXP2101.
No entiendo de programación para poder ayudarte pero creo que si envías algunos cambios al software Antonio podrá probarlo con su placa.
Pude ver en la tabla del link que te envié la comparativa entre los dos chips (AXP192 y AXP2101) y algunas señales son diferentes en ambos, por ejemplo LDO2 y LDO3 que existen en el AXP192 no existen en el AXP2101.
Antonio está en la región de Curitiba - Paraná y yo estoy en Florianópolis - Santa Catarina, estamos montando una red LoRa APRS aquí en Brasil.
Muchas gracias por el fantástico trabajo que ha realizado con este sistema.

Saludos, 73

Mateus PP5FMM

**Comment by richonguzman** [comment]
Como puedo contactar directo para algunas pruebas?

Algún correo?

El 13-06-2023, a las 18:49, Mateus PP5FMM ***@***.***> escribió:

﻿

Ok ricardo,
Quien tiene esta placa v1.2 es Antonio (PU5PWM) que escribió antes. Lo estaba ayudando a instalar Tracker y luego descubrimos que la versión de la placa que había comprado era nueva y con el chip AXP2101.
No entiendo de programación para poder ayudarte pero creo que si envías algunos cambios al software Antonio podrá probarlo con su placa.
Pude ver en la tabla del link que te envié la comparativa entre los dos chips (AXP192 y AXP2101) y algunas señales son diferentes en ambos, por ejemplo LDO2 y LDO3 que existen en el AXP192 no existen en el AXP2101.
Antonio está en la región de Curitiba - Paraná y yo estoy en Florianópolis - Santa Catarina, estamos montando una red LoRa APRS aquí en Brasil.
Muchas gracias por el fantástico trabajo que ha realizado con este sistema.

Saludos, 73

Mateus PP5FMM

**Comment by Mateus-PP5FMM** [comment]
e-mail     qrz.com

**Comment by px5e9142** [comment]
px5e9142@hotmail.com

**Comment by richonguzman** [comment]
did I contact everyone over mail with this?

**Comment by Mateus-PP5FMM** [comment]
> did I contact everyone over mail with this?

Yes!

**Comment by richonguzman** [comment]
Tracker firmware now has the ability to work with T-BEAM v1.1 from 2021 and v1.2 from 2023 with both AXP912 and AXP2101 power chips ;)
