### ISSUE TITLE
T-beam v1.1 sx1268 

### ISSUE THREAD

**Issue by radioman1511** [richonguzman/LoRa_APRS_Tracker#30]
Problem with middle button gpio 38, double Click/press  no function, long press after 7 seconds change the callsign, one click no function. Batterystatus not visible on display. Grts radioman1511

**Comment by richonguzman** [comment]
hi, new version specially for SX1268 board is available now... please test as it is running smooth now for me


please test and confirm

**Comment by radioman1511** [comment]
Now everything works perfect, button and battery info work great and everything is fine. You do wonderful programming work
