### ISSUE TITLE
Shutdown button?

### ISSUE THREAD

**Issue by DO3MBJ** [richonguzman/LoRa_APRS_Tracker#31]
Hi,

maybe this is a stupid question, but how can i shut down the tracker?
If there is a battery inserted it will run until the battery is empty.

Can I shut down the tracker by pressing any of the three buttons without removing the battery every time?

Regards from Germany,
Jürgen

**Comment by ON2ON-HAM** [comment]
If you do a 'LONG' push on the most left button, the ttgo will shut down. Keep pushing until the Oled goes dark
