### ISSUE TITLE
temp not transmitted

### ISSUE THREAD

**Issue by airboxed** [richonguzman/LoRa_APRS_Tracker#32]
At first many thanks for the nice project,
BME280 works, shows temp. pressure. ttc on screen.
but not transmitting to aprs.
regards dan 
vy 72 de DL6OW

**Comment by richonguzman** [comment]
Hi, so far the wx data is not Tx on purpose.  If we send it we would need to do a few changes, wx telemetry/data is only processed when:
- send no more than 1 packet each 9-10 min
- change symbol 

If you are ok with it , it could be added ;)

**Comment by airboxed** [comment]
Thanks for megafast reply. I am OK ! Regards Dan.

**Comment by richonguzman** [comment]
"I'm ok" = "not now" or "please add this" ? 😅

**Comment by airboxed** [comment]
Pleeeeeeaaaaase add ! Many thanks in advance! Dan

**Comment by airboxed** [comment]
Pleaaaaasseee add. Many thanks in advance.
Dan

**Comment by richonguzman** [comment]
Lets go DAN, time to test it , its ready and added!

**Comment by airboxed** [comment]
Thanks so much , I will test now. Regards DAN!

**Comment by airboxed** [comment]
All things work very well.
Thanks and 72 de Dan!
