### ISSUE TITLE
Recommended BME280 module?

### ISSUE THREAD

**Issue by kratinoska** [richonguzman/LoRa_APRS_Tracker#35]
Could you give us type of BME280 module which you are using for?

**Comment by richonguzman** [comment]
I've seen three types of BME280:
Two of them with just 4 pins (the usual I2C connection)
The third different had 6 pins (SDO pin to GND to define the i2C direction)

**Comment by kratinoska** [comment]
and are you planing to add BMP280 into Tracker?

**Comment by richonguzman** [comment]
Yes

Does your BMP280 have only temperature and pressure (without humidity?)?

**Comment by kratinoska** [comment]
I have got this module
https://www.aliexpress.com/item/1005003203897342.html
with humidity :(

**Comment by richonguzman** [comment]
it seems it uses another humidity besides the BMP280 to measure it.

try to find an example which uses the BMP280 and the second chip with libraries and post it to see if we could do something to make It work also
