### ISSUE TITLE
Battery duration

### ISSUE THREAD

**Issue by lostdog2** [richonguzman/LoRa_APRS_Tracker#36]
richonguzman,

another question.

Now I can red the battery percentage.
Leaving the board (LILYGO 1.2) on the table in my office, without GPS coverage (so the board never transmit the position in APRS), I seen the battery discharging quickly.
Starting with full charge at about 10:00, I seen 35% at 15:00, but after this the percentage decrease at 1% at second, and the board shut off.
The battery is an X-Balog , 8800 mAh, very cheap choice, but new, at the second charging cycle.
Is this consumption normal for this board?
Do you have suggestion?

Many Thanks
lostdog

**Comment by richonguzman** [comment]
There are two things to see:
1) without gps fix , gps module consumption is higher because is trying to get the fix
2) you say you have there a 18650 battery with 8800mA??

It's hard to believe this much current in one battery like this

So i would recommend to measure the real values of this battery (with a litokala or good charger just to validate the real values we are talking here)

Let me know how it goes

**Comment by lostdog2** [comment]
Ahah,  agree with you about the battery capacity :-)
Probably the china man that wrote the numbers seen 8800 instead 3300 :-)

How much mA you think I should see from the battery to the board, using multimeter, during normal use?
The display show V and %, not mA.

P.S.
I didn't know litokala, I will oder one.

Many thanks

lostdog

**Comment by richonguzman** [comment]
Axp2101 power management chip does not measure mA like the old AXP912.

So all is voltage measurement (and an aproxímate %) in the T-beam.

Usually a good 18650 is from 2500mA to 3300mA (a really big value is always a lie to me... )

I used this special chargers to measure my 18650's and with 2800 y get easy more than a day worth of tracking

**Comment by lostdog2** [comment]
Ok, many thanks for you informations.

Me too seen the not cheap batteries with about 3000 mA, I bought this only for curiosity :-D

One day of tracking is what I need, planning to use it for my one-day trekkings.
For more than one day, I will carry more than one battery.

Many thanks again
lostdog

**Comment by richonguzman** [comment]
When I bought a 18650 I always try to buy from known stores and even though I measure it right ways for internal resistance and current 

Bad or counterfeit ones get caught right away

**Comment by lostdog2** [comment]
I see many different types of battery chargers from liitokala.
What is the best fo you?
I'ts good for me a 2 or 4 places, powered from 12V car adapter and AC.
What type you know can display capacity and internal resistance?
The Aliexpress description are not so detailed.

**Comment by richonguzman** [comment]
this is the one I have:

[https://es.aliexpress.com/item/1005005446404385.html?spm=a2g0o.productlist.main.3.6463TvrkTvrkpB&algo_pvid=d3ff7d36-85c2-4eca-be66-058dc5cc4c64&algo_exp_id=d3ff7d36-85c2-4eca-be66-058dc5cc4c64-1&pdp_npi=4%40dis%21CLP%2139602%2118132.0%21%21%21302.56%21%21%40210324f116971549273826273eb668%2112000033157703885%21sea%21CL%21173277367%21&curPageLogUid=BLJPVg3rPAey](url)

This one let me measure the charging current, discharging current and internal resistance, although the important factor is always the max current it can produce as this is the result of a healthy internal resistor value

**Comment by lostdog2** [comment]
Thanks for the link.
I ordered now, it will arrive in 2 weeks.

Ciao
lostdog
