### ISSUE TITLE
RF amplifier

### ISSUE THREAD

**Issue by lostdog2** [richonguzman/LoRa_APRS_Tracker#37]
Good afternoon richonguzman.

I seen you have considered one output pin for an external RF amplifier, in order to increase the power of the transmission.
This can be very useful for my needs (localization in mountan paths where is no cellular coverage).
I searched in Internet, and found many devices, mainly two diffeent type:

- specific bi-directional devices, with automatic switching for tx, powered from 3,7 to 5V, that drain about 10 mA if used in automatic mode. In order to save battery, I could switch it ON by using the output pin connected to a mosfet, with delay between power on and tx. But I'm afraid that the rx amplifier will saturate the receiver when I use it in noisy environment.

- general-purpose wide band uni-directional devices. This can be also powered with the same pin and mosfet, but all iI found are powered with 5V or 12V, that are no good, due I would like to use a second 18650 battery dedicated to the amplifier.

Have you experienced with this devices?
I hope to build a small-weight device, in order to don't make my backpack heavier.

Many thanks
lostdog

**Comment by richonguzman** [comment]
I was testing with great results a power amp from 

https://hamparts.shop/vhfuhflora/

they haven't it listed but they will,

contact Jan ;)
