### ISSUE TITLE
Question LILYGO T-Beam S3 Core 22/11/02 V3.0

### ISSUE THREAD

**Issue by AWCowan** [richonguzman/LoRa_APRS_Tracker#38]
All
Just starting the journey with LORA and wish to test range using APRS.
I have bought 2 boards LILYGO T-Beam S3 Core 22/11/02 V3.0 one with screen gps battery etc and one just a board with gps
Will the firmware work with these?
Thanks
Andrew GM0UDL

**Comment by richonguzman** [comment]
Hi, I have not updated this firmware to S3 T-Beam as I have not one yet , so no info as how to make this work right now.

For ALL any help with it would be awesome ;)

**Comment by richonguzman** [comment]
T-Beam S3 Supreme V3 added to supported boards ;)
