### ISSUE TITLE
smart_beacon

### ISSUE THREAD

**Issue by kratinoska** [richonguzman/LoRa_APRS_Tracker#39]
I have set active to false in first beacon and true in second, but when I switch T-beam to second beacon, monitor on USB says [INFO][Main] Smart Beacon is: Off, but should be ON.

"beacons": [
		{
			"callsign": "OK2MNL-14",
			"symbol": "[",
			"overlay": "/",
			"comment": "",
			"smart_beacon": {
				"active": false,
				"slowRate": 120,
				"slowSpeed": 3,
				"fastRate": 60,
				"fastSpeed": 15,
				"minTxDist": 50,
				"minDeltaBeacon": 20,
				"turnMinDeg": 12,
				"turnSlope": 60
			}
		},
		{
			"callsign": "OK2MNL-14",
			"symbol": ">",
			"overlay": "/",
			"comment": "",
			"smart_beacon": {
				"active": true,
				"slowRate": 120,
				"slowSpeed": 10,
				"fastRate": 60,
				"fastSpeed": 70,
				"minTxDist": 100,
				"minDeltaBeacon": 12,
				"turnMinDeg": 10,
				"turnSlope": 80
			}
		},

**Comment by richonguzman** [comment]
Hi, 

do you mean that when you change between calligns (saved on the tracker) it won't change their smarbeacon state? or that the message shown in serial output is faulty?

**Comment by kratinoska** [comment]
it won't change their smarbeacon state

**Comment by paquio** [comment]
Ciao, HI, IZ0JHY Antony @richonguzman
Owner
[richonguzman](https://github.com/richonguzman)

ho caricato lo skect, tutto ok ma lo smartbeacon non funziona l'icona sulla cartina aprs rimane statica e non gira secondo la direzione i dati gps arrivano legorarmente il led rosso lapeggia +8 sattelliti in vista mi puoi aiutare? grazie, lo smartbeacon e true su tutti e tre i nominativi IZ0JHY-9 IZ0JHY-7 IZ0JHY-8 perche non funziona?

**Comment by richonguzman** [comment]
Hi

Are you moving when you say beacons are not being transmitted?

Did you try with just fixed beacon time?

**Comment by paquio** [comment]
Sono in movimento...

⁣Ottieni BlueMail per Android ​

Il giorno 4 dic 2023, 13:29, alle ore 13:29, "Ricardo Guzman (Richonguzman)" ***@***.***> ha scritto:

**Comment by paquio** [comment]
Poi la data che appare sul display risale al 1999-31-12 ???


⁣Ottieni BlueMail per Android ​

Il giorno 4 dic 2023, 13:41, alle ore 13:41, Antonio DI PAOLA ***@***.***> ha scritto:

**Comment by richonguzman** [comment]
Did you try to reset gps data? Sometimes gps needs to be reseted because some older firmware versions of other block the gps 

Can you test sending beacons on a fixed time ? And if it shows on APRS.fi ?

(Please keep on English written as I can't answer fast on the phone with translators ;) )

**Comment by paquio** [comment]
Come posso risolvere 

⁣Ottieni BlueMail per Android ​

Il giorno 4 dic 2023, 13:29, alle ore 13:29, "Ricardo Guzman (Richonguzman)" ***@***.***> ha scritto:

**Comment by paquio** [comment]
Yes I have already reset the GPS 2 times but it is still the same

⁣Ottieni BlueMail per Android ​

Il giorno 4 dic 2023, 13:47, alle ore 13:47, "Ricardo Guzman (Richonguzman)" ***@***.***> ha scritto:

**Comment by richonguzman** [comment]
Let's start by checking a few things:
Does it send Lora packets ? Is the correct board selected in environment?

When put in no smartbeacon , does it send in the correct fixed time?

Validating this is more important than the date on screen as this is just a cosmetic problem (for now)

**Comment by paquio** [comment]
I try to deactivate the smartbeacon on -7 -8 and leave it active only on -9

⁣Ottieni BlueMail per Android ​

Il giorno 4 dic 2023, 13:47, alle ore 13:47, "Ricardo Guzman (Richonguzman)" ***@***.***> ha scritto:

**Comment by richonguzman** [comment]
Find me on telegram as @richonguzman to keep on resolving this ;)

**Comment by paquio** [comment]
Thank Riccardo!

⁣Ottieni BlueMail per Android ​

Il giorno 4 dic 2023, 13:47, alle ore 13:47, "Ricardo Guzman (Richonguzman)" ***@***.***> ha scritto:
