### ISSUE TITLE
Time zone, date format and symbol

### ISSUE THREAD

**Issue by IZ1HMT** [richonguzman/LoRa_APRS_Tracker#4]
It would be useful to have the indication, in addition to the large callsign on the display, also of the symbol (even only in code) of the car, pedestrian, boat, bicycle, etc. It would also be nice to also have the ability to change the time zone and the display to dd-mm-yyyy for various cities in Europe.

**Comment by richonguzman** [comment]
the SYMBOL now can be added next to the CALLSIGN now (just as a character) but its working fine.

the timezone would be a little more complicated but this would be for a next iteration.
