### ISSUE TITLE
T-lora-v2_1 GPS does not disable

### ISSUE THREAD

**Issue by baudrunner** [richonguzman/LoRa_APRS_Tracker#42]
Hi richonguzman, 
thank you for this great software and keep up the nice work.

I found a little name-missmatch of large/lower case in the config file. 

In the file: track_config.json  Line 76 it says:
**"disableGPS": false"**

In X.cpp Files the name of the variable says:
**"Config.disableGps"**

Once the letters are "GPS" and then "Gps", so the variables does not match. I fixed it in the "track_config.json" and changed the name to "disableGps". Now it works, without error on my T-lora-v2_1.

Best wishes and thank you
Chris DM1DW

**Comment by richonguzman** [comment]
thanks for noticing it! just being corrected, wait a few days for other fix added to the code to be on the actual firmware

thanks!
