### ISSUE TITLE
Having trouble getting battery voltage to show for Lilygo TTGO T-Beam T22 v1.1

### ISSUE THREAD

**Issue by radiohound** [richonguzman/LoRa_APRS_Tracker#47]
I have a Lilygo T-Beam T22 v1.1 . I've tried compiling for v1 and version v1_2 and v1, and also v1_sx1268 . It always displays No Battery Connected. Any ideas how to get this working? 

Thank you,

Walter

**Comment by radio-Joe** [comment]
Hi Walter,

the TTGO_T_Beam_V1 configuration will definitly work on your T-Beam T22 V1.1. I use the same board, had same trouble and get rid of it, after PIO, Platform, Erase Flash and upload again V1. 
Good luck.

73 de Josef

**Comment by radiohound** [comment]
That fixed it, thank you!
