### ISSUE TITLE
Settings for SH1106 display

### ISSUE THREAD

**Issue by Citrixon3crx** [richonguzman/LoRa_APRS_Tracker#5]
Dear, 
Would it be possible to get a file for using ttgo with a larger display SH1106?
Thank you very much!

Kind regards,
ON3CRX

**Comment by richonguzman** [comment]
Hi!

do you have this screen already to make some test and look for the library to work this out?

maybe try this library? 

https://github.com/durydevelop/arduino-lib-oled

CD2RXU

**Comment by richonguzman** [comment]
hi, did you resolve this?

I found that you can try to add this:

#define USE_SH1106

on the display.h or display.cpp to try

**Comment by Citrixon3crx** [comment]
Dear,

I'm on vacation now, wensday i try this out.

Thx

Op ma 10 jul. 2023 12:28 schreef Ricardo Guzman (Richonguzman) <
***@***.***>:

**Comment by richonguzman** [comment]
good news!!!


SH1106 screen are now working also , go to "display.cpp" and uncomment line9 to make it work!

**Comment by richonguzman** [comment]
as firmware 2023.08.05 this is available

**Comment by Citrixon3crx** [comment]
Ok, i load the file and i try this out ..
Manny thanks!

ON3CRX

Op za 5 aug 2023 om 17:04 schreef Ricardo Guzman (Richonguzman) <
***@***.***>:

**Comment by Citrixon3crx** [comment]
Dear Ricardo,

Could you look at the settings, because the received signal is the distance
always indicated incorrectly on the igate ...
Example : tracker at a distance of 8km , is on the igate always around
5865km????
The trackers that are with github of OE5BPA do give the correct mileage ...

Manny thx
ON3CRX

Op zo 6 aug 2023 om 23:18 schreef Christophe S ***@***.***>:

**Comment by richonguzman** [comment]
Maybe is it a station hearead before having a fix on the gps?

**Comment by Citrixon3crx** [comment]
It happens with several trackers, ON4CDR has this problem also ...
Personally, I have this with my tracker too.
Both have a good gps signal +12 ...

Op ma 14 aug 2023 om 20:33 schreef Ricardo Guzman (Richonguzman) <
***@***.***>:

**Comment by richonguzman** [comment]
Does this error appears on the syslog info? Or where did you see this on the igate?


I did not get this before as this issue was for the tracker.

**Comment by Citrixon3crx** [comment]
I don't have a syslog server yet , I see this on the igate display and also
on the tracker menu 2 Listen trackers ..
i send you pictures with ON4CDR who is on 5600km and ON3MR at 5 km ( he use
the github from OE5BPA )
ON4CDR see this to that when i transmit the km's is wrong ...

Op di 15 aug 2023 om 03:38 schreef Ricardo Guzman (Richonguzman) <
***@***.***>:
