### ISSUE TITLE
Enhancement suggestion: implement Radiolib function "setRxBoostedGainMode" for SX126x 

### ISSUE THREAD

**Issue by dc1rdb** [richonguzman/LoRa_APRS_Tracker#50]
Radiolib has a function to enable or disable Rx Boosted Gain mode as described in SX126x datasheet
      section 9.6 (SX1261/2 v2.1, SX1268 v1.1)
      \param rxbgm True for Rx Boosted Gain, false for Rx Power Saving Gain

Would it be possible to implement this function, maybe configurable in the "LoRa" section of tracker_config.json?

73 de Robert DC1RDB

**Comment by richonguzman** [comment]
had complete forget about it, and its now into Tracker and iGate ;)

**Comment by dc1rdb** [comment]
Thanks a lot!

**Comment by richonguzman** [comment]
Thank you! Let me know if you see big changes
