### ISSUE TITLE
Adding backup battery charging

### ISSUE THREAD

**Issue by tk5ep** [richonguzman/LoRa_APRS_Tracker#55]
Hi Ricardo,
I've loaded your latest version (31.12) and it works.
But you should add the backup battery charging, otherwise this battery quickly goes flat and then, the GPS fix can be VERY looong.

I've added in setup() in power_utils.cpp the following lines for the AXP2101 modules :
    // Enable Button Battery charge
    PMU.enableButtonBatteryCharge();

    // Set Button Battery charge voltage
    PMU.setButtonBatteryChargeVoltage(3300);

Now, the battery is charging.

I hope this helps.
73, Patrick.

**Comment by richonguzman** [comment]
mod is added for all boards with AXP2101 power management chip on "adding_Heltec_V3_GPS" branch for testing
