### ISSUE TITLE
Tracker doesn't send a WX Telemetry

### ISSUE THREAD

**Issue by lachutm** [richonguzman/LoRa_APRS_Tracker#57]
OLED shows all three values but Telemetry in not send to APRS with the beacon.

"bme": {
		"active": true,
		"sendTelemetry": true,

**Comment by richonguzman** [comment]
on the Wiki :

"sendTelemetry": true enables Wx data to be transmitted to APRS-IS servers and appears as telemetry. Default is false. To Send Telemetry you need both "active":true and "sendTelemetry":true. Please be aware that this forces 10min between Wx data Tx (without affecting the usual GPS data beacon Tx) and also uses a momentary different Symbol for APRS-IS servers to process the beacon packet as Wx data.

take notice on the 10min between Wx beacons (in between the normal Tracker beacons)
