### ISSUE TITLE
Changing timezone

### ISSUE THREAD

**Issue by sp2csr** [richonguzman/LoRa_APRS_Tracker#58]
Is it possible to change the time zone of gps time data?

**Comment by richonguzman** [comment]
hi, the Time Zone is what you receive from GPS, which is UTC time

do you need a special custom Time mod for using in another GMT time zone?

**Comment by sp2csr** [comment]
No no, i need info how to display correct time (for my Loc) on Tracker Display.

**Comment by richonguzman** [comment]
will try to find something, but the data from GPS have always been UTC time , this is why only this is showed.

as far as I know there is no GMT correction available with this library, but will see if I can do something about it

**Comment by iw2ejh** [comment]
May be you refer to the daylight saving time? My tracker show 12:35 while the APRS.FI report the beacon as 13:35..  Now the time here is 13:35.  During summer, the times are aligned.  https://en.wikipedia.org/wiki/Daylight_saving_time_by_country

**Comment by richonguzman** [comment]
yes! satellites only send UTC time, they dont care about your position or daylight time savings. This is a local thing and should be handled this way.

looking for a code mod to enable some corrections about it

**Comment by Szetya** [comment]
Maybe the function setenv() for the system time. It can handle time zones and daylight saving time.

**Comment by richonguzman** [comment]
i don't find it to clear to implement, besides looks not updated for long time.

should this be handled on a self build library o function?

**Comment by Szetya** [comment]
Now I look, this function belongs to the NTP library. Unfortunately, since the tracker has no internet connection, it is not good. :(
