### ISSUE TITLE
Use in static position (no GPS) for simple weather station

### ISSUE THREAD

**Issue by radiohound** [richonguzman/LoRa_APRS_Tracker#60]
Hello, I would like to modify this code to be able to operate without a GPS for a permanently mounted simple temperature, pressure and humidity weather station. Could you help guide me as to what parts of the code I would need to modify? Thank you, 
Walter

**Comment by tk5ep** [comment]
HI,
There are other software that will do what you want.

I've written one that can do your job.
[https://github.com/tk5ep/WX-station-LoRa-WiFi](https://github.com/tk5ep/WX-station-LoRa-WiFi)

I've also just finished a very low power WX station that is consuming only 6-7 microamperes in sleep mode.
It uses an Arduino pro mini and a SX1278 board.
Look on aprs.fi for TK5EP-13 (WX station) and TK5EP-12 (Tiny WX station)

Feel free to contact me.
pegloff[at]gmail.com
