### ISSUE TITLE
Display Eco Mode not working on T-Beam Supreme

### ISSUE THREAD

**Issue by tobiasschwalm** [richonguzman/LoRa_APRS_Tracker#61]
The display does not turn off automatically on the T-Beam Supreme, although the eco mode was enabled, no matter what timeout is configured.

**Comment by richonguzman** [comment]
Hello, the TBeam supreme uses SH1103 board , so far the only library I could find for working with it does not have q way to turn off the screen unless controlled by the powerManagment chip and changing the voltage sended to it

Should we try to have this implemented?

**Comment by richonguzman** [comment]
@tobiasschwalm it should be available and running now, please update all firmware code and it should run without any issue
