### ISSUE TITLE
Android Bluetooth not connecting

### ISSUE THREAD

**Issue by cshoaf** [richonguzman/LoRa_APRS_Tracker#62]
Bluetooth will not pair with Android devices.  Bluetoothtype is set to 1, but does not show up when scanning for device.  Tried it with three different android devices. Tried setting Bluetoothtype to 0 and it shows up, but obviously won't work with Android devices.  Any idea?  Using a Heltec v3.

**Comment by richonguzman** [comment]
it seems Heltec v3 only has BLE and not BT (classic) so unless the Android has BLE it seems you are out of luck

**Comment by aximm** [comment]
I'm haveing exactly the same issue. Heltec v3 doesn't show up when scanning for devices. My phone supports BLE.

**Comment by richonguzman** [comment]
The android part is build with BT classic in mind

I will have to check what to change to use this in android over BLe

**Comment by miodzicho** [comment]
Same with LilyGo T-Beam 32Core SUPREME. Not visible in android BT scan.

**Comment by richonguzman** [comment]
is your Android BLE or BT classic?

**Comment by miodzicho** [comment]
BT5.3 LE so I presume it is BLE

**Comment by richonguzman** [comment]
Just found out APRSDROID only uses SPP and ESP32S3 boards cant do it.... I will still keep on looking
