### ISSUE TITLE
support for Heltec Wireless Tracker

### ISSUE THREAD

**Issue by lachutm** [richonguzman/LoRa_APRS_Tracker#65]
Any chance to add support for this board:
![OIP (1)](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/104542311/c98dbce5-b7e5-4c0e-b409-5535401bb00c)
it's Wireless Tracker kit based on ESP32-S3FN8 with 0.96 inch 160 * 80 LCD display. it runs on SX1262 LoRa chip and UC6580 for GPS.

**Comment by richonguzman** [comment]
Hi,

I would love to add this...

can you help me with needed data to start trying and testing?

like Pinouts and such?

**Comment by lachutm** [comment]
[Wireless Tracker 1.1.pdf](https://github.com/richonguzman/LoRa_APRS_Tracker/files/14297551/Wireless.Tracker.1.1.pdf)
 Most of this is available on their web https://heltec.org/project/wireless-tracker/

**Comment by lachutm** [comment]
Let me know if You need testing on hardware.

**Comment by richonguzman** [comment]
ok, this should be called "HELTEC WIRELESS TRACKER" ?

I found the pinout for:
-LoRa (8,9,10,11,12,13,14)
-GPS / GNSS (33,34,35,36)  (we need to look at how to make it work!)
-BatteryPin 1


- TFT ( 21, 38,39,40,41,42) the TFT could wait for the last part..

do you have telegram to make this faster? (look at my github user at Telegram)

**Comment by HA7CQ** [comment]
I have this panel work well with meshtastic. (GPS work inside the building :) )
When you support this I can help you  to start trying and testing!

**Comment by lachutm** [comment]
Hello I have a two hours now for testing. Letter afternoon I'm leveling, and I will be back late evening.
________________________________

**Comment by Szetya** [comment]
First test. It needs a bit of tweaking. 😇
![IMG_20240220_230557](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/22783982/9ea47c84-5659-4d10-a0c4-b61cf770e8dd)
![IMG_20240220_200926](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/22783982/c93ed944-24eb-4814-be4d-d8e1c793c3b9)

**Comment by Szetya** [comment]
https://github.com/Szetya/LoRa_APRS_Tracker

**Comment by HA7CQ** [comment]
I install it to the heltec wireless tracker 433Mhz panel. Running Wel! Thanks a lot Szetya! 
![IMG_20240223_181949](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/160362797/9e60ff9a-312e-4f6d-bee7-7e1b6dac0c1e)

**Comment by kratinoska** [comment]
> https://github.com/Szetya/LoRa_APRS_Tracker

page does not exists.

**Comment by Szetya** [comment]
> > https://github.com/Szetya/LoRa_APRS_Tracker
> 
> page does not exists.
Perhaps not by chance.

**Comment by richonguzman** [comment]
Heltec Wireless Tracker support added ;)

**Comment by lachutm** [comment]
Thank You :)

**Comment by HA7CQ** [comment]
Hi Ricardo!
I install the last main version to Heltec wirelles tracker.
Work well!
I experienced an error in the display, the symbol does not appear (truck) symbol = "k". Look at the attached photo. 
Thanks your effort!

**Comment by richonguzman** [comment]
hi, the symbols are not displayed, but will be very soon as I have to learn a way to do it on TFT ;)

**Comment by HA7CQ** [comment]
Ok, be good work!

**Comment by Szetya** [comment]
😉
https://youtu.be/DllqYauCWqw?si=-zTdJIhhCmT1JYp9

**Comment by richonguzman** [comment]
symbols added ;)
