### ISSUE TITLE
Missing function when enabling BME680

### ISSUE THREAD

**Issue by MILUX-DE** [richonguzman/LoRa_APRS_Tracker#67]
src/bme_utils.cpp:181:17: error: 'class Adafruit_BME680' has no member named 'takeForcedMeasurement'

**Comment by richonguzman** [comment]
fix uploaded! 

please download again and test it (report back how it went ;)  )

**Comment by MILUX-DE** [comment]
Fix is working!

I've still had to change the BME 680 I²C default address to 0x77, a definition for the device address in bme_utils.h might make sense. Maybe it can be checked during startup which typical I²C device address is present to set it automatically. This might even save to hardcode the corresponding booleans (applicable to CARDKB as well) in config.
