### ISSUE TITLE
Soporte para otras placas (T-beam Supreme, T-Deck)

### ISSUE THREAD

**Issue by sysadminpower2019** [richonguzman/LoRa_APRS_Tracker#69]
Hola como te va.
Veo que ahora hay mas opciones que nunca para LORA y quisiera saber si fuera posible tener soporte para estas nuevas placas tambien. 
Aqui algunos vinculos a los vendedores en aliexpress
https://www.aliexpress.com/item/1005005692235592.html?algo_exp_id=31c4ce0f-7b20-4845-8d3d-8e018a939e6c-11&utparam-url=scene%3Asearch%7Cquery_from%3A
https://www.aliexpress.com/item/1005005975847274.html?algo_exp_id=65cb9faf-0ef4-47aa-a842-709e00128f9c-12&utparam-url=scene%3Asearch%7Cquery_from%3A

**Comment by richonguzman** [comment]
Hola

Estoy intentando aprender del código para poder usar esa también pero es bastante más complicada que el tracker

**Comment by richonguzman** [comment]
tienes una T-deck para probar?

**Comment by Szetya** [comment]
https://youtu.be/FUyCoIiv4gM?si=U9tsrr4c1efssJgE
The display design later... 😉

**Comment by richonguzman** [comment]
> https://youtu.be/FUyCoIiv4gM?si=U9tsrr4c1efssJgE The display design later... 😉

tomorrow I'll share mine :P

**Comment by leonardinux** [comment]
how do you select the T-DECK device here?

![image](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/5922931/1c5e16c7-b21e-44d3-9866-7c12e98027b2)

**Comment by richonguzman** [comment]
hi,

you just add the same boards from guide (TTGO .......)


and after that you change the environment  on VSCODE and it will update and download all the libraries for you
