### ISSUE TITLE
more icons :-)

### ISSUE THREAD

**Issue by DC4FRT** [richonguzman/LoRa_APRS_Tracker#7]
Not an issue but a wish:-)

in the file tracker_config.json:
pls change the position of the variable "overlay": "xxx"
to each callsign.

This will allow us to use more symbols and different for each Callsign.

Thank you really much for your good work.
73 Thomas, DC4FRT

**Comment by richonguzman** [comment]
custom "overlay"  for each callsign added ;)

PS: also new icons/symbol for our motorcycle
