### ISSUE TITLE
Radiolib bandwidth 

### ISSUE THREAD

**Issue by Szetya** [richonguzman/LoRa_APRS_Tracker#75]
https://github.com/richonguzman/LoRa_APRS_Tracker/blob/97122eec5be81d27e255bed83299cfee7fc4c12c/src/lora_utils.cpp#L95

https://github.com/richonguzman/LoRa_APRS_Tracker/blob/97122eec5be81d27e255bed83299cfee7fc4c12c/src/lora_utils.cpp#L48

In radiolib the bandwidth in kHz.

**Comment by richonguzman** [comment]
yes yes! I'm on it very soon!

**Comment by richonguzman** [comment]
corrected ;)
