### ISSUE TITLE
Incrementing comment counter

### ISSUE THREAD

**Issue by gm5dna** [richonguzman/LoRa_APRS_Tracker#77]
Would it be possible to add a function whereby an incrementing counter could be added to the APRS comment so that an assessment could be made of how many tracker packets are being igated? There is another firmware (https://github.com/cfr34k/t-echo-lora-aprs/) which does this, which doesn't have all the other functionality of yours, but I (and maybe some others) would find this helpful.

e.g. https://aprs.fi/?c=raw&call=GM5DNA-8

Thank you!

**Comment by richonguzman** [comment]
so you are asking to add an packet Tx counter to the tracker firmware for testing purposes? or as a constant feature?

**Comment by gm5dna** [comment]
Exactly. To make an assessment of the proportion of packets received by an
igate. Interesting for testing purposes. Far from a core feature request!

**Comment by richonguzman** [comment]
With the syslog possibilities of the igate firmware, adding this to comments is not needed anymore
