### ISSUE TITLE
New bus symbol

### ISSUE THREAD

**Issue by formtapez** [richonguzman/LoRa_APRS_Tracker#78]
Hello,
can we get a symbol for the bus?
Thanks 🚌

`"symbol": "U",
"overlay": "/"`

**Comment by richonguzman** [comment]
will add this soon!

**Comment by sysadminpower2019** [comment]
Could we get a train symbol as well. Very useful in europe

**Comment by richonguzman** [comment]
I completo forgot about this as I was solving other issues, will try to finish all of this soon

**Comment by richonguzman** [comment]
bus and train added
