### ISSUE TITLE
Support also for SX1268 would be great :-)

### ISSUE THREAD

**Issue by DC4FRT** [richonguzman/LoRa_APRS_Tracker#8]
When ordering the boards of the Lora T-Beam, I paid attention to the frequency 430MHz, but unfortunately did not see the difference between SX1278 and SX1268. 
Now I have some SX1268 boards here in my hand which unfortunately do not work. 
Failure is "Error - Starting LoRa failed! "

I have also SX1278, they work really fine :-) great Job from Ricardo.

thanks and best regards
73, Thomas

**Comment by jranma** [comment]
@richonguzman Can you please confirm that SX1268 boards do not work ? 
Would be useful, cheers 73 Julien

**Comment by richonguzman** [comment]
Sx1268 chips will work in the future , right now they don’t (I need one board to further test it )

Saludos,

Ricardo / Richon
(Enviado desde mi celular a tubos)

El 21-07-2023, a las 16:02, jranma ***@***.***> escribió:

﻿

@richonguzman<https://github.com/richonguzman> Can you please confirm that SX1268 boards do not work ?
Would be useful, cheers 73 Julien

**Comment by jranma** [comment]
@richonguzman Thanks for your great work. I sponsored you as a modest contribution to buy the card ;) 
Best 73, Julien

**Comment by richonguzman** [comment]
Great

Will search the way to get one and update all to work

Saludos,

Ricardo / Richon
(Enviado desde mi celular a tubos)

El 21-07-2023, a las 16:17, jranma ***@***.***> escribió:

﻿

@richonguzman<https://github.com/richonguzman> Thanks for your great work. I sponsored you as a modest contribution to buy the card ;)
Best 73, Julien

**Comment by richonguzman** [comment]
I received the board and currently working on it , wait just a little!

**Comment by richonguzman** [comment]
hi, new version specially for SX1268 board is available now... please test as it is running smooth now for me

please test and confirm!

**Comment by kratinoska** [comment]
I got board with SX1268 and seems to me that it does not work well. On radio listening 433.775 is quite different against ordinary T-beam with SX1278 and igate received one packet on power on only. see:
https://aprs.fi/#!mt=roadmap&z=11&call=a%2FOK2MNL-16&timerange=3600&tail=3600

**Comment by richonguzman** [comment]
Hello

My test show Sx1278 listen more than sx1268

But can you explain how your tbeam is not working that well?

And also the igate (I did not get it)

**Comment by Mane76** [comment]
@kratinoska , please consider two things
1) using aprs.fi for determining if an specific iGate has rx you is not feasible. If several iGates do rx you only the "fastest" one will be shown on aprs.fi
2) sx1268 is generally more sensitive in rx compared to sx1278, but does not tolerate big frequency offsets. sx1268 may tolerate +/-3kHz, sx1278 +/-10kHz or even more

For evaluation use Ricardos iGate connected to serial console and transmit with the tracker. Each frame should be visible in the serial console, including the offset.

**Comment by richonguzman** [comment]
My firmware for the igate allows queries:

You send a message to the igate "?ARPSL" and it will answer all the listened stations in the last 30min

**Comment by kratinoska** [comment]
In Brno city we have few iGates based on OE FW.
My T-Beam with SX1268 and Ricardo FW:
I turn on T-beam and only one pocket (possition) was received and shown on Aprs.fi
https://aprs.fi/#!mt=roadmap&z=11&call=a%2FOK2MNL-16&timerange=3600&tail=3600
T-beam was on during my way to work (approx 20 minutes). And no other "mark" shown on maps....

**Comment by richonguzman** [comment]
can you explain it better, I did not get your testing scenario or your configuration of the tracker

**Comment by kratinoska** [comment]
probably bad koax connection between t-beam and antena, ...

**Comment by kratinoska** [comment]
confirmed. With new cable it works very well.
