### ISSUE TITLE
Winlink stopped or paused too much time... and not connect

### ISSUE THREAD

**Issue by linuxnt** [richonguzman/LoRa_APRS_Tracker#80]
Hi!

Today update my T-Beam to the latest firmware version. Many things works fine except WinLink.

If I attempt to login to **WinLink**, the T-Beam **still waiting** post request sended. The previous version worked fine.

What is the possible clue to solve the problem?

TNX VY 73 de XE2XEH

**Comment by richonguzman** [comment]
Hola!

1) to start any process like Winlink you have to reach a Rx+Tx igate
2) yo need to be sure the igate has heard a gps beacon of yours in the last 30 min , this allows the igate to Tx back to you all the messages from WLNK-1 to your tracker
3) do you have a valid winlink password (has it 6 letters?)
