### ISSUE TITLE
Feature request "wind speed and direction"

### ISSUE THREAD

**Issue by joevk5ei** [richonguzman/LoRa_APRS_Tracker#82]
A request if it would be possible to read sensor data from a wind vane and wind speed, then forward to aprs network. 

This would be the perfect solution for a remote aprs wx station (with wind measurements)

**Comment by richonguzman** [comment]
Hi,

I'm working currently on a full Wx station with Wind Direction, Speed, Rain and many other sensors.... I will update as soon as I can.

**Comment by tk5ep** [comment]
Hi,
If someone is interested in a WX station, I've written my own that has following main features : 
- APRS LoRa
- APRS-IS
- MQTT
- Wunderground
- Web server
- etc...

73, Patrick TK5EP
https://egloff.eu
