### ISSUE TITLE
Add instructions for programming via terminal / command line

### ISSUE THREAD

**Issue by NeoFromMatrix** [richonguzman/LoRa_APRS_Tracker#87]
It would be nice if someone could add instructions on how to compile, program and upload the config via linux command line /terminal.

I assume the commands are;

1. Compile firmware and upload
`$  pio run -e ttgo-t-beam-v1_2 -t upload`

2. Upload filesystem (build spiffs.bin based on "data" folder and upload)
`$ pio run -t uploadfs`

Can anyone verify the commands are correct? 

Edit: Changed text

**Comment by richonguzman** [comment]
Hi ,  I would love to !

but I dont know much "command line" commands for vscode/esptool or the ways to do it.

but I would love to learn and apply this

**Comment by richonguzman** [comment]
im adding very soon webflasher with web configuration page to avoid VSCODE and terminal flashing ;)
