### ISSUE TITLE
posibilidad modificar hora UTC 

### ISSUE THREAD

**Issue by sysadminpower2019** [richonguzman/LoRa_APRS_Tracker#95]
Hola,

Queria preguntarte si no seria posibile de agregar una opcion para modificar la hora UTC que sale en el display.

Seria bueno tener la hora local ya sea via GPS o alguna opcion directamente en el modulo

Gracias

**Comment by richonguzman** [comment]
Hola,

los gps solo envian hora UTC, no hay zonas horarias para la info que ellos envian.

**Comment by sysadminpower2019** [comment]
Ah gracias por la info. Entonces quizas se podria agregar algun parametro en la programacion o en el menu para poder ajustar la hora

**Comment by richonguzman** [comment]
esto es meramente cosmetico : lo dejare en las cosas por hacer, pero nada de lo pronto/urgente

**Comment by sysadminpower2019** [comment]
Si quieres mandar me tu discord para conversar un poco y ver si mejoramos la documentacion y el plan de trabajo

**Comment by richonguzman** [comment]
puede ser por telegram ? me es infinitamente mas cómodo (porque no uso discord hahahaha) 

mi usuario es el mismo de aqui para que me encuentres ;)
